n = int(input('Введите четырехзначное число: '))
a = int((round(n)/1000))
b = int((round(n)/100) % 10)
c = int((n // 10) % 10)
d = int(n % 10) 
print('First number:', a)
print('Second number:', b)
print('Third number:', c)
print('Fourth number:', d)
